// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameApplication = "applications"

// Application mapped from table <applications>
type Application struct {
	ID        string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Version   string    `gorm:"column:version" json:"version"`
	AppType   string    `gorm:"column:app_type" json:"app_type"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName Application's table name
func (*Application) TableName() string {
	return TableNameApplication
}
