// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDevice = "devices"

// Device mapped from table <devices>
type Device struct {
	ID               string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	DeviceIdentifier string    `gorm:"column:device_identifier;not null" json:"device_identifier"`
	Description      string    `gorm:"column:description" json:"description"`
	Status           string    `gorm:"column:status" json:"status"`
	LastSeen         time.Time `gorm:"column:last_seen" json:"last_seen"`
	CreatedAt        time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	GroupID          string    `gorm:"column:group_id" json:"group_id"`
}

// TableName Device's table name
func (*Device) TableName() string {
	return TableNameDevice
}
