// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDeviceApplication = "device_applications"

// DeviceApplication mapped from table <device_applications>
type DeviceApplication struct {
	DeviceID      string    `gorm:"column:device_id;primaryKey" json:"device_id"`
	ApplicationID string    `gorm:"column:application_id;primaryKey" json:"application_id"`
	InstalledAt   time.Time `gorm:"column:installed_at;not null;default:now()" json:"installed_at"`
}

// TableName DeviceApplication's table name
func (*DeviceApplication) TableName() string {
	return TableNameDeviceApplication
}
