// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStatus = "statuses"

// Status mapped from table <statuses>
type Status struct {
	ID        string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Name      string    `gorm:"column:name" json:"name"`
	Code      string    `gorm:"column:code;not null" json:"code"`
	Context   string    `gorm:"column:context;not null" json:"context"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName Status's table name
func (*Status) TableName() string {
	return TableNameStatus
}
