// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Username     string    `gorm:"column:username;not null" json:"username"`
	Email        string    `gorm:"column:email;not null" json:"email"`
	PasswordHash string    `gorm:"column:password_hash;not null" json:"password_hash"`
	RoleCode     string    `gorm:"column:role_code" json:"role_code"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
