// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDeviceGroup = "device_groups"

// DeviceGroup mapped from table <device_groups>
type DeviceGroup struct {
	ID          string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Description string    `gorm:"column:description" json:"description"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName DeviceGroup's table name
func (*DeviceGroup) TableName() string {
	return TableNameDeviceGroup
}
