// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMetric = "metrics"

// Metric mapped from table <metrics>
type Metric struct {
	ID              string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	DeviceID        string    `gorm:"column:device_id" json:"device_id"`
	PublicIP        string    `gorm:"column:public_ip" json:"public_ip"`
	Hostname        string    `gorm:"column:hostname" json:"hostname"`
	OsInfo          string    `gorm:"column:os_info" json:"os_info"`
	DiskTotal       int64     `gorm:"column:disk_total" json:"disk_total"`
	DiskUsed        int64     `gorm:"column:disk_used" json:"disk_used"`
	DiskFree        int64     `gorm:"column:disk_free" json:"disk_free"`
	MemoryTotal     int64     `gorm:"column:memory_total" json:"memory_total"`
	MemoryUsed      int64     `gorm:"column:memory_used" json:"memory_used"`
	MemoryAvailable int64     `gorm:"column:memory_available" json:"memory_available"`
	ProcessCount    int32     `gorm:"column:process_count" json:"process_count"`
	CPUPercent      float32   `gorm:"column:cpu_percent" json:"cpu_percent"`
	BytesSent       int64     `gorm:"column:bytes_sent" json:"bytes_sent"`
	BytesRecv       int64     `gorm:"column:bytes_recv" json:"bytes_recv"`
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName Metric's table name
func (*Metric) TableName() string {
	return TableNameMetric
}
